name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cppunit
        run: sudo apt-get install -y libcppunit-dev

      - name: Make configure script executable
        run: chmod +x ./configure

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Test
        run: make test
